name: Auto Push Python Files

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"  # Das pusht jede Stunde

jobs:
  push:
    runs-on: Auto
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Actions"
          git add *.py
          git commit -m "Automatisches Update"
          git push origin main
